# Generated by Django 3.0.6 on 2020-05-31 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200601_0007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile1',
            new_name='Profile',
        ),
    ]
