# Generated by Django 3.0.6 on 2020-06-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200601_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='useR',
        ),
    ]
